Issue-#115 Add support for TC transfer frames
NASA-AMMOS/AIT-DSN pull request #153
Opened 2022-02-09 18:02 UTC by Mejiro-McQueen

Add Support for TCTF:

1. TCTF Definitions
2. TCTF Encoder
3. TCTF Decoder
4. TCTF Manager Plugin
5. TCTF Encode/Decode Tests
6. TCTF Readme

Verified and validated against SunRISE FSWS

2022-02-10 15:27 UTC, MJJoyce requested changes
Thanks very much for the PR @Mejiro-McQueen! Small feedback / change requests around the plugin / stream approach but nothing major.

2022-02-10 15:27 UTC, MJJoyce commented on ait/dsn/plugins/TCTF_Manager.py
> +        ait.core.log.error(f"TCTF_Manager: {encoded_frame}")
This does look like an `error`. Probably `debug`.

2022-02-10 15:40 UTC, Mejiro-McQueen commented on ait/dsn/plugins/TCTF_Manager.py
> +                    - 666
You're right, I thought it would convey what you stated, but I think it just adds confusion. 
I've removed it entirely.

2022-02-15 20:54 UTC, nttoole approved these changes

2022-02-15 20:54 UTC, merged