Harness start invocation should send entire time value
NASA-AMMOS/AIT-DSN pull request #178
Opened 2022-05-02 17:13 UTC by jasonmlkang

**Included in this PR:**
- [x] send entire time value in raf.py and rcf.py

**Refs:**
- Original ticket: #138

2022-05-02 17:28 UTC, nttoole requested changes
@jasonmlkang Could we wrap the new code as a common method that takes a time, and optionally an offset (which defaults to the CCSDS_EPOCH)?

2022-05-18 20:37 UTC, jasonmlkang commented
> @jasonmlkang Could we wrap the new code as a common method that takes a time, and optionally an offset (which defaults to the CCSDS_EPOCH)?

Done in e58784d

2022-05-23 16:40 UTC, jasonmlkang commented
@nttoole Unit tests add in 9b3b9dd. PR is ready for review.

2022-05-24 22:07 UTC, nttoole approved these changes

2022-05-24 23:46 UTC, merged